kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: dc-soundclown
  namespace: soundclown
spec:
  selector:
    app: soundclown
  replicas: 1
  template:
    metadata:
      labels:
        app: soundclown
    spec:
      containers:
        - name: soundclown
          image: stream-soundclown
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: soundclown
              mountPath: /opt/app/destination
      restartPolicy: Always
      volumes:
        - name: soundclown
          persistentVolumeClaim:
            claimName: pvc-sc-data
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - soundclown
        from:
          kind: ImageStreamTag
          namespace: soundclown
          name: 'stream-soundclown:latest'