kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: stream-soundclown
  namespace: soundclown
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'thisisnttheway/soundclown:latest'
      generation: 2
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source