kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sc-data
  namespace: soundclown
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storage:
    class: thin