apiVersion: v1
kind: Service
metadata:
  name: svc-soundclown
  namespace: soundclown
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: soundclown
  type: LoadBalancer